# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HWWzec3eFu-WXHF327wTh7B1GPLVTkIn
"""

import streamlit as st

st.write('Hello World')